version: "3"
services:   
  manage-web: 
    container_name: web
    build: 
      context: .
      dockerfile: Convience.Web/Managent/Dockerfile
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./config/config.json:/usr/share/nginx/html/assets/config/config.json
  manage-api-1:
    container_name: api-1
    build: 
      context: .
      dockerfile: Convience.Applications/Convience.ManagentApi/Dockerfile
    restart: always
    ports:
      - "5001:80"
    volumes:
      - ./config/appsettings.json:/app/appsettings.json
  manage-api-2:
    container_name: api-2
    build: 
      context: .
      dockerfile: Convience.Applications/Convience.ManagentApi/Dockerfile
    restart: always
    ports:
      - "5002:80"
    volumes:
      - ./config/appsettings.json:/app/appsettings.json
  myproject-nginx: 
    container_name: my-nginx
    image: nginx
    restart: always
    ports: 
      - "80:80"
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  myproject-pgsql: 
    container_name: pgsql
    image: postgres
    restart: always
    privileged: true
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: tester
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: tester
    volumes: 
      - ./conf/data:/var/lib/postgresql/data

